#This creates the namespace, rbac requirements and the bigip service 
#
#kubectl create serviceaccount bigip-ctlr -n kube-system
#
# for use in k8s clusters only
# for OpenShift, use the OpenShift-specific examples

---
apiVersion: v1
kind: Namespace
metadata:
  name: bigip-ingress

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigip-ctlr
  namespace: bigip-ingress

---  

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole
  namespace: bigip-ingress
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  resourceNames: ["bigip-login1"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bigip-ctlr-clusterrole-binding
  namespace: bigip-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-ctlr-clusterrole
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: bigip-ctlr
  namespace: bigip-ingress

---
apiVersion: v1
kind: Secret
metadata:
  name: bigip-login1
  namespace: kube-system
type: Opaque
data:
  username: bWFjbWlsbGFu
  password: VDVodXVqMG9qZ2pnRkY=

---
